import { getExplorerUrl } from "@/lib/utils";
import Link from "next/link";

export const siteConfig = {
	title: "Croak Clash",
	description: "A frog-themed decentralized battleground on the Linea blockchain where various frog factions battle for control of limited resources.",
	url: "https://croak-clash.vercel.app",
	ogImage: "https://croak-clash.vercel.app/og.png",
	links: {
		twitter: "https://twitter.com/croakclash",
		github: "https://github.com/yourusername/croak-clash",
	},
	keywords: [
		"blockchain",
		"web3",
		"game",
		"frog",
		"nft",
		"linea",
		"ethereum",
		"defi",
		"gaming",
		"crypto",
		"battleground",
		"evolution",
		"faction",
		"warrior",
		"battle",
		"resource",
		"management",
		"token",
		"staking",
		"rewards",
	],
	authors: [
		{
			name: "Your Name",
			url: "https://github.com/yourusername",
		},
	],
	creator: "Your Name",
	openGraph: {
		type: "website",
		locale: "en_US",
		url: "https://croak-clash.vercel.app",
		title: "Croak Clash – Frog Warriors Battle for Swamp Supremacy",
		description: "A frog-themed decentralized battleground on the Linea blockchain where various frog factions battle for control of limited resources.",
		siteName: "Croak Clash",
		images: [
			{
				url: "https://croak-clash.vercel.app/og.png",
				width: 1200,
				height: 630,
				alt: "Croak Clash",
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		title: "Croak Clash – Frog Warriors Battle for Swamp Supremacy",
		description: "A frog-themed decentralized battleground on the Linea blockchain where various frog factions battle for control of limited resources.",
		images: ["https://croak-clash.vercel.app/og.png"],
		creator: "@croakclash",
	},
	icons: {
		icon: "/favicon.ico",
		shortcut: "/favicon-16x16.png",
		apple: "/apple-touch-icon.png",
	},
	manifest: "/site.webmanifest",
	masterAddress: process.env.NEXT_PUBLIC_MASTER_ADDRESS,
	croakTokenAddress: process.env.NEXT_PUBLIC_CROAK_TOKEN_ADDRESS,
	frogNFTAddress: process.env.NEXT_PUBLIC_FROG_NFT_ADDRESS,
	croakClashAddress: process.env.NEXT_PUBLIC_CROAK_CLASH_ADDRESS,
};
